# Generated by Django 3.2.23 on 2024-01-27 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ECGModel',
            fields=[
                ('id', models.AutoField(help_text='A unique identifier for each ECG', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='The date of creation')),
                ('leads', models.JSONField(help_text='List of leads')),
            ],
        ),
        migrations.CreateModel(
            name='LeadsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The lead identifier', max_length=50)),
                ('num_samples', models.IntegerField(blank=True, help_text='The sample size of the signal', null=True)),
                ('signal', models.JSONField(help_text='A list of integer values')),
                ('ecg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connector.ecgmodel')),
            ],
        ),
    ]
