# Generated by Django 3.2.23 on 2024-01-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='second_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
