# Generated by Django 3.2.23 on 2024-01-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0002_ecgmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='name',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
    ]
