version: '3.8'

services:
  app:
    build: .
    image: ecg
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - APP_ENV=development

  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=idoven_ecg
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
