# Generated by Django 3.2.18 on 2023-04-29 14:31

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electrocardiogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('samples', models.IntegerField()),
                ('signal', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('electrocardiogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.electrocardiogram')),
            ],
        ),
    ]
